### ISSUE TITLE
No success with short example

### ISSUE THREAD

**Issue by kswope** [melito/em-syslog#5]
Is there some trick to getting this to work?  Since this is a short example I wonder if
EM's internal workings are exercised enough to get things flushed.  The standard ruby syslog library works fine.  Unfortunately I can't compare and contrast to the standard ruby library because its written in c.  I've tried this on both linux and osx.  On linux I turned the firewall off, on osx, who knows.

```
!/usr/bin/env ruby

require 'em/syslog'
require 'syslog/logger'

require 'eventmachine'

class EchoServer < EM::Connection
  def receive_data(data)
    send_data(data)
  end
end

EventMachine.run do

  # hit Control + C to stop
  Signal.trap("INT")  { EventMachine.stop }
  Signal.trap("TERM") { EventMachine.stop }

  EM.syslog_setup('127.0.0.1', 514)
  EM.info 'from em syslog' # <-- nothing

  EM.syslog_setup('localhost', 514)
  EM.info 'from em syslog' # <-- nothing

  EM.syslog_setup('0.0.0.0', 514)
  EM.info 'from em syslog' # <-- nothing

  log = Syslog::Logger.new 'my_program'
  log.info "from regular syslog" # <-- works!

  EventMachine.start_server("0.0.0.0", 10000, EchoServer)

end
```

**Comment by melito** [comment]
Apologies for the delay in this - The echo server in the example kind of threw me.

When you say 'nothing' is happening, do you mean nothing is showing up in your machine's logs?
Without knowing what syslog daemon is running, what port its on, if its opting to use tcp over udp, what log it's configured to write to, etc I don't think I can be of much assistance.

However, you can give this a shot:

Look at the example here: https://github.com/melito/em-syslog/blob/master/test.rb
Uncomment the open_datagram_socket bit and run the example.  
You should see the server start logging messages.

The idea is to verify that there isn't something getting gunked up in EM and the client is actually sending out syslog format udp messages.  Once you're able to verify that, I suggest that you look into your syslog config to confirm messages are being written to the log you're expecting and a syslog daemon is listening on 514

**Comment by kswope** [comment]
Success!  Thanks for your guidance

For any dopes like me out there reading this.  rsyslog, at least on centos(redhat), is not setup by default to receive UDP messages.  Everything you see dumping crap into your logs is probably calling /bin/logger, including the standard ruby module Syslog.  You do not want to use any file IO with eventmachine!  (at least not directly, thats why we are using syslog to log for us)

try looking in /etc/rsyslog.conf, these two lines need uncommenting
$ModLoad imudp
$UDPServerRun 514

**Comment by melito** [comment]
Excellent! Glad I could help.

Marking this as closed - Thanks for the rsyslog info
